#!/bin/bash
# Author: Craig Hesling
# Date: August 6, 2015
#
# Usage: listenpubsub <node> [xmpp_jid [xmpp_pass]]

# If xmpprc file, import XMPPTOOLS, XMPP_JID, and XMPP_PASS
if [ -f xmpprc ]; then
	. xmpprc
fi

# nodeid first argument
NODE=$1
# if no jid and pass specified use xmpprc or env
XMPP_JID=${2:-$XMPP_JID}
XMPP_PASS=${3:-$XMPP_PASS}
# default to ..
XMPPTOOLS=${XMPPTOOLS:-..}

# import functions
. $XMPPTOOLS/xmppcmd.bash $XMPP_JID $XMPP_PASS

xml_newline() {
	# We do a real newline for compatibility with OSX
	sed 's/></>\
</g'
}

$XMPPTOOLS/xmpprecv `get_jid` `get_pass` -p $@ | \
	{
		while read line; do
			# Raw Output
			#echo $line

			# Line Separated
			echo $line | xml_newline

			# Pretty Print
			#echo $line | xml_prettyprint

			echo
		done
	}
