#!/bin/bash
# Author: Craig Hesling
# Date: August 5, 2015
#
# Usage: listenall [xmpp_jid [xmpp_pass [filter_name [filter_type [filter_ns]]]]]

# If xmpprc file, import XMPPTOOLS, XMPP_JID, and XMPP_PASS
if [ -f xmpprc ]; then
	. xmpprc
fi

# if no jid and pass specified use xmpprc or env
XMPP_JID=${1:-$XMPP_JID}
XMPP_PASS=${2:-$XMPP_PASS}
# default to ..
XMPPTOOLS=${XMPPTOOLS:-..}

# import functions
. $XMPPTOOLS/xmppcmd.bash $XMPP_JID $XMPP_PASS

xml_newline() {
	# We do a real newline for compatibility with OSX
	sed 's/></>\
</g'
}

shift 2
$XMPPTOOLS/xmpprecv `get_jid` `get_pass` -s $@ | \
	{
		while read line; do
			# Raw Output
			#echo $line

			# Line Separated
			echo $line | xml_newline

			# Pretty Print
			#echo $line | xml_prettyprint

			echo
		done
	}

# vim: syntax=sh ts=4
