#!/bin/bash
# Author: Craig Hesling
# Date: August 5, 2015

XMPP_JID=bob@example.com
XMPP_PASS=bobspassword

# import functions
. ../xmppcmd.bash >/dev/null

../xmpprecv $XMPP_JID $XMPP_PASS -s | \
	{
		while read line; do
			# raw ouput
			echo $line
			# attempt pretty print
			#echo $line | xml_prettyprint
			echo
		done
	}
