#!/bin/bash
# Author: Craig Hesling
# Date: August 5, 2015

# import functions
. ../xmppcmd.bash >/dev/null

../xmpprecv bob@example.com bobspassword -h | \
	{
		while read line; do
			# raw ouput
			echo $line
			# attempt pretty print
			#echo $line | xml_prettyprint
			echo
		done
	}
